### PR TITLE
include more clarity and type checking on data types

### PR DESCRIPTION
**Pull request by alexrudd2**
I'm trying to make controllers more robust to type mismatches in the configuration while rewriting `interface.py` and `config.py`

[example here](https://github.com/alexrudd2/controllers/blob/solvent-recovery-new/controllers/solvent_recovery/config.py#L69-L76)

### CODE REVIEW

**Comment by patrickfuller** [comment]
Looks great!!

Seconding James. Update the version in `setup.py` to `0.2.7`, as this is what allows `pip install` to recognize a new version is available. Copying the datatype checking is also a good idea for added robustness, and can be mostly lifted from the productivity driver.

**Comment by alexrudd2** [comment]
If we want to stay compatible with python3.5, revert daea9cb and modify my [new string](https://github.com/numat/clickplc/pull/7/commits/493f08e4b0178f6cb2b3837e110524eaaf600249#diff-c9a06fe96f6666c184be998af49fde17R90)

Couldn't see any reason to use `pymodbus 2.2.0rc1` release candidate instead of final.

I didn't have a way of testing this until James' brand new `mock.py`

**Comment by JamesJeffryes** [comment]
@alexrudd2 So I changed the base branch to merge your changes into my branch (not master) to get access to unit tests and CI. I had to resolve a conflict by pushing to your branch.

They revealed a typo in your code here: https://github.com/numat/clickplc/pull/7/files#diff-c9a06fe96f6666c184be998af49fde17R191 A missing bracket. You can fix it by pushing a new commit.

**Comment by patrickfuller** [comment]
> Couldn't see any reason to use pymodbus 2.2.0rc1 release candidate instead of final.

Be careful with this! Pymodbus is rough around the edges and I've had [complaints](https://github.com/riptideio/pymodbus/issues?q=author%3Apatrickfuller). I saw a drop in code quality a couple years back when repo ownership moved from someone in Germany to someone in India, and I got the feeling that the new coder was far junior to the original maintainer. They were constantly releasing broken versions, and this 2.2.0rc1 was the last version I was able to use (rc2 didn't work).

If the newest pymodbus works, that's great. BUT test reading/writing on real hardware before changing, and, even then, make sure the dependency version is fixed.

**Comment by alexrudd2** [comment]
Neither James nor I could initially find the changelog from rc1 to release, but I eventually found it on the github releases:

- Fix to task cancellations and CRC errors for async serial clients.
- Fix passing serial settings to asynchronous serial server.
- Fix BinaryPayloadDecoder.to_coils and BinaryPayloadBuilder.fromCoils methods.
- Fix erroneous CRC handling in Modbus RTU framer.
- Support broadcasting in Modbus Client and Servers (sync).
- Improved logging in Modbus Server .
- ReportSlaveIdRequest would fetch information from Device identity instead of hardcoded Pymodbus.
- Fix regression introduced in 2.2.0rc2 (Modbus sync client transaction failing)

I assume only a real idiot would break things in a point release from a release candidate but we'll check.

**Comment by alexrudd2** [comment]
Also, I just wanted to point out James' inclusion of tests caught its very first regression within ONE MINUTE of being pushed.  :+1:  (our commits were very close to each other).

**Comment by patrickfuller** [comment]
@alexrudd2 I'm still impressed at how quickly you've gotten up to speed on this stuff!

I'm willing to accept this PR as is if you don't delete the `rc1` from the pymodbus requirement. While it's probably fine, I'd like to see the dependency change in a separate PR tied to the issue you added.

**Pull request merged**
